### PR TITLE
Fragments and noncritical

### LINKED ISSUE #9: Error when user writes undefined step def in feature
```java
ava.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.jetbrains.plugins.cucumber.completion.TagContext.isContextChanger(TagContext.java:106)
	at org.jetbrains.plugins.cucumber.steps.AbstractCucumberExtension.getTagEntities(AbstractCucumberExtension.java:58)
	at org.jetbrains.plugins.cucumber.steps.AbstractCucumberExtension.resolveStep(AbstractCucumberExtension.java:34)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.multiResolveInner(CucumberStepReference.java:98)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.access$100(CucumberStepReference.java:24)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference$MyResolver.resolve(CucumberStepReference.java:145)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference$MyResolver.resolve(CucumberStepReference.java:140)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:150)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:180)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.multiResolve(CucumberStepReference.java:90)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.resolve(CucumberStepReference.java:50)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:371)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:349)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:223)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:195)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### PR DESCRIPTION
**Pull request by kosteman**
* implement resolve and completion fragments
* support non critical steps
* fix #9

### CODE REVIEW

File: gherkin-tag/src/org/jetbrains/plugins/cucumber/completion/CucumberCompletionContributor.java [hunk 1]
```diff
@@ -117,6 +118,9 @@ protected void addCompletions(@NotNull CompletionParameters parameters,
             protected void addCompletions(@NotNull CompletionParameters parameters,
                                           @NotNull ProcessingContext context,
                                           @NotNull CompletionResultSet result) {
+                if (TagCompletionUtils.addFragments(parameters, result)) {
+                    return;
+                }
                 if (TagCompletionUtils.addPageTitles(parameters, result)) {
                     return;
                 }
```
Comment (clicman) [inline gherkin-tag/src/org/jetbrains/plugins/cucumber/completion/CucumberCompletionContributor.java]:
```
if (TagCompletionUtils.addFragments(parameters, result) ||
TagCompletionUtils.addPageTitles(parameters, result😂 {
     return;
}
```

File: gherkin-tag/src/org/jetbrains/plugins/cucumber/completion/TagCompletionUtils.java [hunk 2]
```diff
@@ -80,6 +81,27 @@ static boolean addEndpointTitles(@NotNull CompletionParameters parameters, @NotN
         return false;
     }
 
+    static boolean addFragments(@NotNull CompletionParameters parameters, @NotNull CompletionResultSet result) {
+        PsiElement element = parameters.getPosition().getContext();
+        String stepName = element instanceof GherkinStepImpl ? ((GherkinStepImpl) element).getStepName() : null;
+
+        if (element instanceof GherkinStep && ((GherkinStep) element).findDefinitions().stream().allMatch(AbstractStepDefinition::isFragment)) {
```
Comment (clicman) [inline gherkin-tag/src/org/jetbrains/plugins/cucumber/completion/TagCompletionUtils.java]: `boolean isFargment = ((GherkinStep) element).findDefinitions().stream().allMatch(AbstractStepDefinition::isFragment);`
